/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Audrey
 */
public class AffichageAABRI extends javax.swing.JFrame {

    private static AffichageAABRI affichageAABRI2;
    /**
     * Creates new form AffichageAABRI2
     */
    private AffichageAABRI() {
        initComponents();
    }

    public static AffichageAABRI getInstance(){
        if(affichageAABRI2 == null){
            affichageAABRI2 = new AffichageAABRI();
        }
        return affichageAABRI2;
    }

    public JTextArea getT_AABRI() {
        return T_AABRI;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_OK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_AABRI = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_OK.setText("OK");
        B_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OKActionPerformed(evt);
            }
        });

        T_AABRI.setColumns(20);
        T_AABRI.setRows(5);
        jScrollPane1.setViewportView(T_AABRI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(B_OK))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_OK)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_B_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_OK;
    private javax.swing.JTextArea T_AABRI;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
