/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Class.GrandArbre;
import GestionAABRI.*;
import Utilitaire.AABRIException;
import Utilitaire.FiltreFichier;
import java.awt.Container;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileFilter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Audrey
 */
public class Menu extends javax.swing.JFrame {

    private static Menu menu;
    private ArrayList AABRIS;
    /**
     * Creates new form Menu
     */
    
    public static Menu getInstance(){
        if (menu == null){
            menu = new Menu();
        }
        return menu;
    }
    private Menu() {
        initComponents();
        AABRIS = new ArrayList();
    }

    public ArrayList getAABRIS() {
        return AABRIS;
    }

    public void setAABRIS(ArrayList AABRIS) {
        this.AABRIS = AABRIS;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_FichierVersAabri = new javax.swing.JButton();
        B_aabriVersFichier = new javax.swing.JButton();
        B_aabrisAleatoire = new javax.swing.JButton();
        B_verifierAabri = new javax.swing.JButton();
        CB_lstAABRI = new javax.swing.JComboBox();
        B_InsererValeur = new javax.swing.JButton();
        B_SupprimerValeur = new javax.swing.JButton();
        B_afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        B_FichierVersAabri.setText("Générer un AABRI à partir d'un fichier");
        B_FichierVersAabri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FichierVersAabriActionPerformed(evt);
            }
        });

        B_aabriVersFichier.setText("Ecrire un AABRI dans un fichier");
        B_aabriVersFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_aabriVersFichierActionPerformed(evt);
            }
        });

        B_aabrisAleatoire.setText("Générer un AABRI aléatoire");
        B_aabrisAleatoire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_aabrisAleatoireActionPerformed(evt);
            }
        });

        B_verifierAabri.setText("Vérifier si l'arbre d'arbres est un AABRI");
        B_verifierAabri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_verifierAabriActionPerformed(evt);
            }
        });

        CB_lstAABRI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        B_InsererValeur.setText("Insérer une valeur");
        B_InsererValeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_InsererValeurActionPerformed(evt);
            }
        });

        B_SupprimerValeur.setText("Supprimer une valeur");
        B_SupprimerValeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SupprimerValeurActionPerformed(evt);
            }
        });

        B_afficher.setText("Afficher AABRI");
        B_afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_afficherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CB_lstAABRI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_FichierVersAabri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_aabriVersFichier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_aabrisAleatoire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_verifierAabri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_InsererValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_SupprimerValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_afficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CB_lstAABRI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_FichierVersAabri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_aabriVersFichier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_aabrisAleatoire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_verifierAabri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_InsererValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_SupprimerValeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_afficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_FichierVersAabriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FichierVersAabriActionPerformed
        JFileChooser chooser = new JFileChooser();
        String fichier = "";
	chooser.setApproveButtonText("Ouvrir"); 
        chooser.changeToParentDirectory();
	if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
    	{	
            fichier = chooser.getSelectedFile().getAbsolutePath(); 
             GrandArbre unGrandArbre = FichierVersAABRI.lireFichier(fichier);
            AABRIS.add(unGrandArbre);
            reinitialiserListe();
            JOptionPane.showMessageDialog(this, "L'arbre a été généré avec succès");
	}else{
            JOptionPane.showMessageDialog(this, "Aucun fichier n'a été sélectionné");
        }
        
        
       
    }//GEN-LAST:event_B_FichierVersAabriActionPerformed

    private void B_aabrisAleatoireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_aabrisAleatoireActionPerformed
        GrandArbre unGrandArbre = new GrandArbre();
        try {
            unGrandArbre = AABRIAleatoire.genererGrandArbre(5, 100);
        } catch (AABRIException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        AABRIS.add(unGrandArbre);
        JOptionPane.showMessageDialog(this, "L'arbre a été généré avec succès");
        reinitialiserListe();
    }//GEN-LAST:event_B_aabrisAleatoireActionPerformed

    private void B_aabriVersFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_aabriVersFichierActionPerformed
        FileWriter fw = null;
        JFileChooser chooser = new JFileChooser();
        String fichier = "";
        GrandArbre unGrandArbre = (GrandArbre)CB_lstAABRI.getSelectedItem();
        chooser.changeToParentDirectory();
        chooser.setFileFilter(new FiltreFichier(new String[]{"txt"},"les fichiers texte (*.txt)"));
	if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
    	{	
            try {
                fichier = chooser.getSelectedFile().getAbsolutePath();
                File fichier2 = new File(fichier);
                fw = new FileWriter(fichier2);
                AABRIVersFichier.ecrireFichier(unGrandArbre, fw);                
                fw.close();
                JOptionPane.showMessageDialog(this, "Le fichier a été généré");
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
	}else{
            JOptionPane.showMessageDialog(this, "Aucun emplacement n'a été sélectionné");
        }
        
    }//GEN-LAST:event_B_aabriVersFichierActionPerformed

    private void B_verifierAabriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_verifierAabriActionPerformed
        GrandArbre unGrandArbre = (GrandArbre)CB_lstAABRI.getSelectedItem();
        if(VerifierAABRI.isAABRI(unGrandArbre)){
            JOptionPane.showMessageDialog(this, "L'arbre est un AABRI");
        }else{
            JOptionPane.showMessageDialog(this, "L'arbre n'est pas un AABRI"); 
        }
        
    }//GEN-LAST:event_B_verifierAabriActionPerformed

    private void B_InsererValeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_InsererValeurActionPerformed
        GrandArbre unGrandArbre = (GrandArbre)CB_lstAABRI.getSelectedItem();
       int i = CB_lstAABRI.getSelectedIndex();
       AABRIS.remove(i);
       String valeur  = JOptionPane.showInputDialog(this, "Saississer une valeur entière positive:");
        try {
            unGrandArbre = ManipulationAABRI.insererValeur(unGrandArbre, Integer.parseInt(valeur));
        } catch (AABRIException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
       AABRIS.add(unGrandArbre);
       reinitialiserListe();
    }//GEN-LAST:event_B_InsererValeurActionPerformed

    private void B_SupprimerValeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SupprimerValeurActionPerformed
       GrandArbre unGrandArbre = (GrandArbre)CB_lstAABRI.getSelectedItem();
       int i = CB_lstAABRI.getSelectedIndex();
       AABRIS.remove(i);
       String valeur  = JOptionPane.showInputDialog(this, "Saississer une valeur entière positive:");
        try {
            unGrandArbre = ManipulationAABRI.supprimerValeur(unGrandArbre,Integer.parseInt(valeur));
        } catch (AABRIException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
       AABRIS.add(unGrandArbre);
       reinitialiserListe();
    }//GEN-LAST:event_B_SupprimerValeurActionPerformed

    private void B_afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_afficherActionPerformed
       GrandArbre unGrandArbre = (GrandArbre)CB_lstAABRI.getSelectedItem(); 
       ArrayList AABRI = AABRIVersFichier.afficherArbreTab(unGrandArbre);
       for(int i =0; i< AABRI.size(); i++){
            AffichageAABRI.getInstance().getT_AABRI().append((String)AABRI.get(i));
            AffichageAABRI.getInstance().getT_AABRI().append("\r\n");
       }
       AffichageAABRI.getInstance().getT_AABRI().setEditable(false);
       AffichageAABRI.getInstance().setEnabled(true);
       AffichageAABRI.getInstance().setVisible(true);
       //JOptionPane.showMessageDialog(this, AABRIVersFichier.afficherArbre(unGrandArbre));
    }//GEN-LAST:event_B_afficherActionPerformed

    private void reinitialiserListe(){
        int i;
        CB_lstAABRI.removeAllItems();
        for(i = 0; i< AABRIS.size(); i++){
            CB_lstAABRI.addItem(AABRIS.get(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_FichierVersAabri;
    private javax.swing.JButton B_InsererValeur;
    private javax.swing.JButton B_SupprimerValeur;
    private javax.swing.JButton B_aabriVersFichier;
    private javax.swing.JButton B_aabrisAleatoire;
    private javax.swing.JButton B_afficher;
    private javax.swing.JButton B_verifierAabri;
    private javax.swing.JComboBox CB_lstAABRI;
    // End of variables declaration//GEN-END:variables
}
